### ISSUE TITLE
Vim theme

### ISSUE THREAD

**Issue by uetchy** [holodata/ancient-one-dark#1]
index: https://vimcolorschemes.com
^ We are likely to need a separate repo for a vim theme

**Comment by Chooks22** [comment]
Looking at their repos, it's mostly just extra terminal themes. Should it still live in another repo?

**Comment by uetchy** [comment]
I'm fine with either, but yeah, let's just stick with monorepo since it has less maintenance burden.

**Comment by uetchy** [comment]
@Choooks22 What's the current status? Let me know if you need some help!
